spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aitourism?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.aitourism.entity
  configuration:
    map-underscore-to-camel-case: true